version: "3"
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: secret
    restart: always
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  web:
    build: .
    ports:
      - "8080:5000"
    depends_on:
      db:
        condition: service_healthy
